// Lol
kr = {
	"apple": "사과",
	"air": "공기",
	"conditioner": "컨디셔너",
	"airport": "공항",
	"ambulance": "구급차",
	"aircraft": "항공기",
	"apartment": "아파트",
	"arrow": "화살",
	"antlers": "뿔",
	"alligator": "악어",
	"architect": "건축가",
	"ankle": "발목",
	"armchair": "안락 의자",
	"aunt": "이모",
	"ball": "공",
	"bermudas": "버뮤다 반바지",
	"beans": "콩",
	"balloon": "풍선",
	"bear": "곰",
	"blouse": "블라우스",
	"bed": "침대",
	"bread": "빵",
	"black": "검은",
	"board": "판",
	"bones": "뼈",
	"bill": "계산서",
	"bitterness": "신랄",
	"boxers": "의화단",
	"belt": "벨트",
	"brain": "뇌",
	"buffalo": "물소",
	"bird": "새",
	"baby": "아가",
	"book": "책",
	"back": "뒤로",
	"butter": "버터",
	"bulb": "구근",
	"buckles": "버클",
	"bat": "박쥐",
	"bank": "은행",
	"bag": "가방",
	"bra": "브래지어",
	"boots": "부츠",
	"blazer": "블레이저",
	"bikini": "비키니",
	"bookcase": "책장",
	"bookstore": "서점",
	"bus stop": "버스 정류장",
	"brass": "놋쇠",
	"brother": "동료",
	"boy": "소년",
	"blender": "블렌더",
	"bucket": "버킷",
	"bakery": "빵집",
	"bridge": "다리",
	"boat": "보트",
	"car": "차",
	"cow": "소",
	"cap": "캡",
	"cooker": "요리 도구",
	"cheeks": "궁둥이",
	"cheese": "치즈",
	"credenza": "크 덴차",
	"carpet": "양탄자",
	"crow": "까마귀",
	"crest": "문장",
	"chest": "가슴",
	"chair": "의자",
	"candy": "사탕",
	"cabinet": "내각",
	"cat": "고양이",
	"coffee": "커피",
	"children": "어린이",
	"cookware": "조리기구",
	"chaise longue": "긴 의자",
	"chicken": "치킨",
	"casino": "카지노",
	"cabin": "선실",
	"castle": "성",
	"church": "교회에",
	"cafe": "카페",
	"cinema": "영화",
	"choker": "높은 칼라",
	"cravat": "넥타이",
	"cane": "지팡이",
	"costume": "복장",
	"cardigan": "카디건",
	"chocolate": "초콜릿",
	"crib": "어린이 침대",
	"couch": "침상",
	"cello": "첼로",
	"cashier": "출납원",
	"composer": "작곡가",
	"cave": "동굴",
	"country": "국가",
	"computer": "컴퓨터",
	"canoe": "카누",
	"clock": "시계",
	"dog": "개",
	"deer": "사슴",
	"donkey": "당나귀",
	"desk": "책상",
	"desktop": "데스크톱",
	"dress": "드레스",
	"dolphin": "돌고래",
	"doctor": "의사",
	"dentist": "치과 의사",
	"drum": "북",
	"dresser": "옷장",
	"designer": "디자이너",
	"detective": "형사",
	"daughter": "딸",
	"egg": "계란",
	"elephant": "코끼리",
	"earrings": "귀걸이",
	"ears": "귀",
	"eyes": "눈",
	"estate": "재산",
	"finger": "손가락",
	"fox": "여우",
	"frock": "드레스",
	"frog": "개구리",
	"fan": "부채",
	"freezer": "냉동고",
	"fish": "물고기",
	"film": "필름",
	"foot": "발",
	"flag": "깃발",
	"factory": "공장",
	"father": "아버지",
	"farm": "농장",
	"forest": "숲",
	"flower": "꽃",
	"fruit": "과일",
	"fork": "포크",
	"grapes": "포도",
	"goat": "염소",
	"gown": "겉옷",
	"garlic": "마늘",
	"ginger": "생강",
	"giraffe": "기린",
	"gauva": "가우 바",
	"grains": "작살",
	"gas station": "주유소",
	"garage": "차고",
	"gloves": "장갑",
	"glasses": "안경",
	"gift": "선물",
	"galaxy": "은하",
	"guitar": "기타",
	"grandmother": "할머니",
	"grandfather": "할아버지",
	"governor": "지사",
	"girl": "소녀",
	"guest": "손님",
	"hamburger": "햄버거",
	"hand": "손",
	"head": "머리",
	"hair": "머리",
	"heart": "심장",
	"house": "집",
	"horse": "말",
	"hen": "암탉",
	"horn": "뿔",
	"hat": "모자",
	"hammer": "망치",
	"hostel": "호스텔",
	"hospital": "병원",
	"hotel": "호텔",
	"heels": "뒷굽",
	"herbs": "허브",
	"host": "숙주",
	"jacket": "재킷",
	"jersey": "저지",
	"jewelry": "보석류",
	"jaw": "턱",
	"jumper": "점퍼",
	"judge": "판사",
	"juicer": "무대 조명 담당자",
	"keyboard": "건반",
	"kid": "아이",
	"kangaroo": "캥거루",
	"koala": "코알라",
	"knife": "칼",
	"lemon": "레몬",
	"lion": "사자",
	"leggings": "레깅스",
	"leg": "다리",
	"laptop": "휴대용 퍼스널 컴퓨터",
	"library": "도서관",
	"lamb": "양고기",
	"london": "런던",
	"lips": "입술",
	"lung": "폐",
	"lighter": "거룻배",
	"luggage": "짐",
	"lamp": "램프",
	"lawyer": "변호사",
	"mouse": "쥐",
	"monkey": "원숭이",
	"mouth": "입",
	"mango": "망고",
	"mobile": "변하기 쉬운",
	"milk": "우유",
	"music": "음악",
	"mirror": "거울",
	"musician": "음악가",
	"mother": "어머니",
	"man": "남자",
	"model": "모델",
	"mall": "쇼핑 센터",
	"museum": "박물관",
	"market": "시장",
	"moonlight": "월광",
	"medicine": "의학",
	"microscope": "현미경",
	"newspaper": "신문",
	"nose": "코",
	"notebook": "수첩",
	"neck": "목",
	"noodles": "국수",
	"nurse": "간호사",
	"necklace": "목걸이",
	"noise": "소음",
	"ocean": "대양",
	"ostrich": "타조",
	"oil": "기름",
	"orange": "주황색",
	"onion": "양파",
	"oven": "오븐",
	"owl": "올빼미",
	"paper": "종이",
	"panda": "팬더",
	"pants": "바지",
	"palm": "손바닥 안에 감추다",
	"pasta": "파스타",
	"pumpkin": "호박",
	"pharmacist": "제약사",
	"potato": "감자",
	"parfume": "향수",
	"panther": "표범",
	"pad": "인주",
	"pencil": "연필",
	"pipe": "파이프",
	"police": "경찰",
	"pen": "펜",
	"pharmacy": "조제",
	"petrol station": "주유소",
	"police station": "경찰서",
	"parrot": "앵무새",
	"plane": "평면",
	"pigeon": "비둘기",
	"phone": "전화",
	"peacock": "공작",
	"pig": "돼지",
	"pouch": "작은 주머니",
	"pagoda": "탑",
	"pyramid": "피라미드",
	"purse": "지갑",
	"pancake": "팬케이크",
	"popcorn": "팝콘",
	"piano": "피아노",
	"physician": "내과 의사",
	"photographer": "사진 작가",
	"professor": "교수",
	"painter": "화가",
	"park": "공원",
	"plant": "식물",
	"radio": "라디오",
	"razor": "면도칼",
	"ribs": "갈비 살",
	"rainbow": "무지개",
	"ring": "반지",
	"rabbit": "토끼",
	"rice": "쌀",
	"refrigerator": "냉장고",
	"remote": "먼",
	"restaurant": "레스토랑",
	"road": "도로",
	"surgeon": "외과 의사",
	"scale": "규모",
	"shampoo": "샴푸",
	"sink": "싱크대",
	"salt": "소금",
	"shark": "상어",
	"sandals": "샌들",
	"shoulder": "어깨",
	"spoon": "숟가락",
	"soap": "비누",
	"sand": "모래",
	"sheep": "양",
	"sari": "사리",
	"stomach": "위",
	"stairs": "계단",
	"soup": "수프",
	"shoes": "구두",
	"scissors": "가위",
	"sparrow": "참새",
	"shirt": "셔츠",
	"suitcase": "가방",
	"stove": "난로",
	"snowman": "눈사람",
	"shower": "샤워",
	"swan": "백조",
	"suit": "소송",
	"sweater": "스웨터",
	"smoke": "연기",
	"skirt": "치마",
	"sofa": "소파",
	"socks": "양말",
	"stadium": "경기장",
	"skyscraper": "마천루",
	"school": "학교",
	"sunglasses": "색안경",
	"slippers": "슬리퍼",
	"shorts": "반바지",
	"sandwich": "샌드위치",
	"strawberry": "딸기",
	"spaghetti": "스파게티",
	"shrimp": "새우",
	"saxophone": "색소폰",
	"sister": "여자 형제",
	"son": "아들",
	"singer": "가수",
	"senator": "평의원",
	"street": "거리",
	"supermarket": "슈퍼마켓",
	"swimming pool": "수영장",
	"star": "별",
	"sky": "하늘",
	"sun": "태양",
	"ship": "배",
	"smile": "미소",
	"table": "표",
	"turkey": "터키",
	"tie": "넥타이",
	"toes": "발가락",
	"truck": "트럭",
	"train": "기차",
	"taxi": "택시",
	"tiger": "호랑이",
	"trousers": "바지",
	"tongue": "혀",
	"television": "텔레비전",
	"teacher": "선생",
	"turtle": "터틀",
	"tablet": "태블릿",
	"train station": "기차역",
	"toothpaste": "치약",
	"tail": "꼬리",
	"theater": "극장",
	"trench coat": "트렌치 코트",
	"tea": "차",
	"tomato": "토마토",
	"teen": "비탄",
	"tunnel": "터널",
	"temple": "신전",
	"town": "도시",
	"toothbrush": "칫솔",
	"tree": "나무",
	"toy": "장난감",
	"tissue": "조직",
	"telephone": "전화",
	"underwear": "속옷",
	"uncle": "삼촌",
	"umbrella": "우산",
	"vest": "조끼",
	"voice": "목소리",
	"veterinarian": "수의사",
	"villa": "별장",
	"violin": "바이올린",
	"village": "마을",
	"vehicle": "차량",
	"vase": "병 장식",
	"wallet": "지갑",
	"wolf": "늑대",
	"waist": "허리",
	"wrist": "손목",
	"water melon": "수박",
	"whale": "고래",
	"water": "물",
	"wings": "날개",
	"whisker": "수염 결정",
	"watch": "손목 시계",
	"woman": "여자",
	"washing machine": "세탁기",
	"wheelchair": "바퀴 달린 의자",
	"waiter": "웨이터",
	"wound": "상처",
	"xylophone": "목금",
	"zebra": "얼룩말",
	"zoo": "동물원"
}

function walk(rootNode)
{
    // Find all the text nodes in rootNode
    var walker = document.createTreeWalker(
        rootNode,
        NodeFilter.SHOW_TEXT,
        null,
        false
    ),
    node;

    // Modify each text node's value
    while (node = walker.nextNode()) {
        handleText(node);
    }
}

function handleText(textNode) {
  textNode.nodeValue = replaceText(textNode.nodeValue);
}

function replaceText(v)
{
    if (kr[v.toLowerCase()] != undefined)
    {
        console.log("Found " + v + " to be " + kr[v.toLowerCase()])
        v = kr[v.toLowerCase()]
    }

    return v;
}

// Returns true if a node should *not* be altered in any way
function isForbiddenNode(node) {
    return node.isContentEditable || // DraftJS and many others
    (node.parentNode && node.parentNode.isContentEditable) || // Special case for Gmail
    (node.tagName && (node.tagName.toLowerCase() == "textarea" || // Some catch-alls
                     node.tagName.toLowerCase() == "input"));
}

// The callback used for the document body and title observers
function observerCallback(mutations) {
    var i, node;

    mutations.forEach(function(mutation) {
        for (i = 0; i < mutation.addedNodes.length; i++) {
            node = mutation.addedNodes[i];
            if (isForbiddenNode(node)) {
                // Should never operate on user-editable content
                continue;
            } else if (node.nodeType === 3) {
                // Replace the text for text nodes
                handleText(node);
            } else {
                // Otherwise, find text nodes within the given node and replace text
                walk(node);
            }
        }
    });
}

// Walk the doc (document) body, replace the title, and observe the body and title
function walkAndObserve(doc) {
    var docTitle = doc.getElementsByTagName('title')[0],
    observerConfig = {
        characterData: true,
        childList: true,
        subtree: true
    },
    bodyObserver, titleObserver;

    // Do the initial text replacements in the document body and title
    walk(doc.body);
    doc.title = replaceText(doc.title);

    // Observe the body so that we replace text in any added/modified nodes
    bodyObserver = new MutationObserver(observerCallback);
    bodyObserver.observe(doc.body, observerConfig);

    // Observe the title so we can handle any modifications there
    if (docTitle) {
        titleObserver = new MutationObserver(observerCallback);
        titleObserver.observe(docTitle, observerConfig);
    }
}
walkAndObserve(document);
